endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

logging.level.root: ERROR
logging.level.org.springframework.web: ERROR
logging.level.com.eason: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.138:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database:  0
# Redis服务器地址
spring.redis.host:  192.168.0.138
# Redis服务器连接端口
spring.redis.port:  6379
# Redis服务器连接密码（默认为空）
spring.redis.password:  zbredis
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0
#TestOnBorrow设置为false，导致有时获取的连接不可用
spring.redis.testOnBorrow:  false

#请求处理的超时时间  
ribbon.ReadTimeout: 60000  
#请求连接的超时时间  
ribbon.ConnectTimeout: 30000  

feign.hystrix.enabled: false  
#hystrix 熔断机制  
hystrix:  
  shareSecurityContext: true  
  command:  
    default:  
      circuitBreaker:  
        sleepWindowInMilliseconds: 100000  
        forceClosed: true  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 600000