endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.138:8761/eureka/
server:
  port: 8769

spring:
  application:
    name: service-zuul
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

zuul:
  routes:
    api:
      path: /api/**
      serviceId: service-feign
    task:
      path: /task/**
      serviceId: service-scheduler

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000