endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

logging.level.root: ERROR
logging.level.org.springframework: INFO
logging.level.com.eason: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 80

spring:
  application:
    name: service-zuul
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

zuul:
  routes:
    api:
      path: /api/**
      serviceId: service-feign
    task:
      path: /task/**
      serviceId: service-scheduler

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000