endpoints.shutdown.enabled: true
endpoints.shutdown.sensitive: false

spring.jpa.database:  mysql
spring.jpa.show-sql:  false

logging.level.root: ERROR
logging.level.org.springframework.web: WARN
logging.level.com.eason: ERROR

spring.datasource.url:  jdbc:mysql://192.168.0.138:3306/qvod?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: root
spring.datasource.password: redhat789
spring.datasource.driver-class-name:  com.mysql.jdbc.Driver

spring.data.mongodb.uri:  mongodb://zb:zbmongo@192.168.0.138:27017/zb

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database:  0
spring.redis.database10:  10
# Redis服务器地址
spring.redis.host:  192.168.0.138
# Redis服务器连接端口
spring.redis.port:  6379
# Redis服务器连接密码（默认为空）
spring.redis.password:  zbredis
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: -1
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 0
#TestOnBorrow设置为false，导致有时获取的连接不可用
spring.redis.testOnBorrow:  false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.138:8761/eureka/
server:
  port: 8762
  tomcat:
        uri-encoding: UTF-8
zb:
  file:
      img:
        local:  /usr/local/tomcat-1/webapps/img/
#        local:  D:/img/
        remote: http://192.168.0.138:8080/img/

spring:
  application:
    name: service-api-zb-impl
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

platfrom:
  media:
    host: 192.168.0.127
    regAccountMap:
      url: http://${platfrom.media.host}/BetSvr/ssvr/RegAccount
      username: test
      password: test
    rtmpUrl: http://${platfrom.media.host}/BetSvr/ssvr/GetRtmpUrl
    recRecords: http://${platfrom.media.host}/BetSvr/ssvr/GetRecRecords
    deleteRecFile: http://${platfrom.media.host}/BetSvr/ssvr/rec/delete

  im:
    host: 192.168.0.138:8080
    regAccountMap:
      url: http://${platfrom.im.host}/MsgServer/apis/auth.php
      username: 1
      password: 2
    imUrl: http://${platfrom.im.host}/MsgServer/apis/address.php

